server:
  port: 8080
spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:/Users/liaishan/workspace/FDU_CS_ms/Software_eng/H2DB/UserDB #自己的目录
    username: sa #数据库用户名，默认sa
    password:  #数据库密码
  jpa:
    database: h2
    hibernate:
      ddl-auto: update
  h2:
    console:
      path: /h2-console #控制台访问路径
      enabled: true
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB